### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ineichp** [tget4/nexx-garage-sdk#6]
Hello, I am 16 years old and I really want to integrate the NEXX into the Openhab system for our garage. But have no experience with JSON / JavaScript and how to implement the code in the description. If I use the install code: npm i nexx-garage-sdk, the following is always attached anyway.
Can I ask for help?
<img width="822" alt="Screenshot 2020-11-16 at 18 55 03" src="https://user-images.githubusercontent.com/63945232/99289556-6ce51280-283d-11eb-909f-aa1962793365.png">

**Comment by tget4** [comment]
Hello - this package is meant to be used inside of a node application. I specifically use it here: https://github.com/tget4/node-red-contrib-nexx-garage. The above error is because you ran the command in a directory without a package.json file.
